//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_BApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IzvozB_sEntities : DbContext
    {
        public IzvozB_sEntities()
            : base("name=IzvozB_sEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authorization> Authorizations { get; set; }
        public virtual DbSet<DailyEntry> DailyEntries { get; set; }
        public virtual DbSet<Date> Dates { get; set; }
        public virtual DbSet<Exporter> Exporters { get; set; }
        public virtual DbSet<Prediction> Predictions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
